### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by Jos512** [felicianotech/hugonewsletter.com#18]
Given that Chrome and FireFox plan to label non-SSL sites as insecure (see [here](https://blog.cloudflare.com/https-or-bust-chromes-plan-to-label-sites-as-not-secure/) for more), it's important that the hugonewsletter.com website gets a SSL certificate.

It also helps to give people confidence in the website (it just looks more professional), especially since the website asks them for their email address. (I know that the Mailchimp form uses SSL, but perceptions also matter.)

**Comment by felicianotech** [comment]
HugoNewsletter.com already has TLS if you use the URL. There just wasn't a redirect but I just implemented it now.

**Comment by Jos512** [comment]
I cannot load hugonewsletter.com now anymore; there's a redirect loop from `hugonewsletter.com` to `https://hugonewsletter.com//`. Pingdom [also](https://tools.pingdom.com/#!/cRWPM5/hugonewsletter.com) has trouble.

**Comment by felicianotech** [comment]
Fixed
